version: 2
working_directory: &working_directory ~/workspace

jobs:
    publish:
        docker:
            - image: circleci/node:8
        working_directory: *working_directory
        steps:
            - checkout
            - run:
                name: Publish
                command: |
                    npm version 1.2.0-beta.2
                    sh ./git.sh
                    echo 'Complete!!'

workflows:
    version: 2
    tagged-build:
        jobs:
            - publish:
                filters:
                    branches:
                        only: /test/
