version: 2
working_directory: &working_directory ~/workspace

jobs:
    publish:
        docker:
            - image: circleci/node:8
        working_directory: *working_directory
        steps:
            - checkout
            - restore_cache:
                # 采用 build_node_8 master
                key: mobx-di-build_node_8-master-{{ checksum "package.json" }}
            - run:
                name: Build
                command: |
                    npm i
                    npm run ci
            - run:
                name: Publish
                command: |
                    npm version 1.2.0-beta.1
                    sh ./git.sh
                    echo 'Complete!!'

workflows:
    version: 2
    tagged-build:
        jobs:
            - publish:
                filters:
                    branches:
                        only: /test/
